config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :events
  resources :communities
  resources :sites
  resources :comunas
  resources :profiles

  get 'sites/comuna/load_sites', to: 'sites#load_sites', as: :load_sites

  get 'communities/comuna/load_communities', to: 'communities#load_communities', as: :load_communities

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :mix_categories
  has_many :communities, through: :mix_categories

  has_many :mix_categories
  has_many :sites, through: :mix_categories

  has_many :mix_categories
  has_many :events, through: :mix_categories
end

app/models/community.rb
class Community < ApplicationRecord
  # has_many :community_sites, class_name: 'CommunitySite'
  # has_many :sites, through: :community_sites
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User'

  has_many :maul_plans
  has_many :sites, through: :maul_plans

  has_many :community_mauls
  has_many :events, through: :community_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture
end

app/models/community_maul.rb
class CommunityMaul < ApplicationRecord
  belongs_to :community
  belongs_to :event
end

app/models/community_site.rb
class CommunitySite < ApplicationRecord
  belongs_to :communities, class_name: 'Community'
  belongs_to :sites, class_name: 'Site'
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  has_many :community, class_name: 'Community'
  has_many :site
  has_many :event
end

app/models/event.rb
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User', optional: true

  has_many :mix_categories
  has_many :communities, through: :community_mauls

  has_many :site_mauls
  has_many :sites, through: :site_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture

end

app/models/maul_plan.rb
class MaulPlan < ApplicationRecord
  belongs_to :community
  belongs_to :site
end

app/models/mix_category.rb
class MixCategory < ApplicationRecord
  belongs_to :community
  belongs_to :site
  belongs_to :event
  belongs_to :category
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  # validates_uniqueness_of :user_id
  # validates_uniqueness_of :profile, scope: :nickname, :message => "Nombre de usuario no disponible"
  # validate :nickname_uniqueness

  # protected
  
  # def nickname_uniqueness
  #   errors.add(:nickname, 'Nombre de usuario no disponible') if Profile.where('nickname' => nickname).exists?
  # end
end

app/models/site.rb
class Site < ApplicationRecord
  # has_many :community_sites, class_name: 'CommunitySite'
  # has_many :communities, through: :community_sites
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User', optional: true

  has_many :maul_plans
  has_many :communities, through: :maul_plans
  accepts_nested_attributes_for :communities, allow_destroy: true

  has_many :site_mauls
  has_many :events, through: :site_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture
end

app/models/site_maul.rb
class SiteMaul < ApplicationRecord
  belongs_to :site
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # extend FriendlyId
  # friendly_id :name, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :profile, depent: :destroy
  has_one :profile
  after_create :create_profile

  has_many :community, class_name: 'Community'
  has_many :site, class_name: 'Site'
  has_many :event, class_name: 'Event'

  def create_profile
    Profile.create(user: self)
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # layout 'communities/layout'

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  def load_communities
    @comuna = Comuna.find(params[:comuna_id])
    @communities = Community.where(comuna_id: @comuna)
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'La comunidad se creo satisfactoriamente' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Comunidad actualizada satisfactoriamente' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :about, :address, :phone, :email, :facebook, :instagram, :twitter, :youtube, :website, :comuna_id, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
  def verifyFields(community)
    if community.address.present?
      1
    else
      23
    end
  end
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  NETWORKS = [
    'website',
    'facebook',
    'instagram',
    'twitter',
    'youtube'
  ]
  def networks_section(site)
    links = []
    # NETWORKS.each do |n|
      # case site[:n].present?
      # when true
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end
      # if site[:n] != nil
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end

      # site[:n].present? == true ? links << content_tag(:i, image_tag("icons/#{n}.svg")) : nil

      # links << content_tag(:i, image_tag("icons/#{n}.svg"))
    # end
    if site.website.present?
      links << content_tag(:i, link_to(image_tag("icons/website.svg"), site.website, target: '_blank', class: 'link-svg'))
    end
    if site.facebook.present?
      links << content_tag(:i, link_to(image_tag("icons/facebook.svg"), site.facebook, target: '_blank', class: 'link-svg'))
    end
    if site.twitter.present?
      links << content_tag(:i, link_to(image_tag("icons/twitter.svg"), site.twitter, target: '_blank', class: 'link-svg'))
    end
    if site.instagram.present?
      links << content_tag(:i, link_to(image_tag("icons/instagram.svg"), site.instagram, target: '_blank', class: 'link-svg'))
    end
    if site.youtube.present?
      links << content_tag(:i, link_to(image_tag("icons/youtube.svg"), site.youtube, target: '_blank', class: 'link-svg'))
    end
    links.join.html_safe
  end
end

app/views/communities/smartphone/_index.html.haml
.m.index-communities
  .bg-bar-community
    .container.d-flex.justify-content-between.mt-2
      %h1.d-flex.align-items-center= link_to t('base.communities'), communities_path, alt: 'index communities', class: 'link-white'
      %h2.d-flex.align-items-center
        %em.link-white.fa.fa-users.mr-2
        %em= link_to t('community.create_a_community'), new_community_path, class: 'link-white'
  %p#notice= notice

  .d-flex.justify-content-center
    %ul#tabCommunities.nav.nav-tabs{:role => "tablist"}
      %li.nav-item
        %a#all-tab.nav-link.active{"aria-controls" => "all", "aria-selected" => "true", "data-toggle" => "tab", :href => "#all", :role => "tab", class: 'link-community' } Todas
      %li.nav-item
        %a#category-tab.nav-link{"aria-controls" => "category", "aria-selected" => "false", "data-toggle" => "tab", :href => "#category", :role => "tab", class: 'link-community' } Categorías
      %li.nav-item
        %a#comunas-tab.nav-link{"aria-controls" => "comunas", "aria-selected" => "false", "data-toggle" => "tab", :href => "#comunas", :role => "tab", class: 'link-community' } Comunas

  #tabCommunitiesContent.tab-content
    #all.tab-pane.fade.show.active{"aria-labelledby" => "all-tab", :role => "tabpanel"}
      .container
        - @communities.each do |community|
          .box-index.card.p-2.mt-4
            %blockquote.blockquote.mb-0
              .card-body.bg-card
                - if community.picture.attached?
                  = image_tag community.picture
                - else
                  = image_tag 'https://42f2671d685f51e10fc6-b9fcecea3e50b3b59bdc28dead054ebc.ssl.cf5.rackcdn.com/illustrations/good_team_m7uu.svg', width: '50%'
                =link_to community.name, community, class: 'card-title'
              -# %footer
                .text-right temática 1, temática 2...

    #category.tab-pane.fade{"aria-labelledby" => "category-tab", :role => "tabpanel"} ...
    #comunas.tab-pane.fade{"aria-labelledby" => "comunas-tab", :role => "tabpanel"} ...

app/views/communities/smartphone/_show.html.haml
.show-community
  %nav{"aria-label" => "breadcrumb"}
    .bg-bar-community
      .container
        %ol.breadcrumb
          %li.breadcrumb-item
            %a.link-white{:href => "/"}
              %i.fas.fa-home
          %li.breadcrumb-item
            %a.link-white{:href => communities_path}= t('base.communities')
          %li.breadcrumb-item.active{"aria-current" => "page"}= @community.name
  .container.text-center
    %p#notice= notice
    - if user_signed_in? && current_user.id == @community.user_id
      .show-community-edit
        = link_to edit_community_path(@community), class: 'link-dark' do
          %i.fa.fa-edit
    %h1.mt-3= @community.name
    %hr.mb-2
    .community-networks-section
      = networks_section @community
    .mt-3= image_tag(@community.picture, width: 200) if @community.picture.attached?
    .mt-3.card
      .card-body.text-left
        %strong= t('community.about_community')
        %p
          = @community.about

        - if @community.maul_plans.count > 0
          %em ¿Dónde nos reunimos?
          %p
            - @community.maul_plans.each do |community_site|
              = link_to community_site.site.name, community_site.site
              %br
        - elsif @community.address.present?
          %em ¿Dónde nos reunimos?
          %p= @community.address

        - if @community.phone.present?
          %em Teléfono(s) de contacto:
          %p= @community.phone

        - if @community.email.present?
          %em correo electrónico:
          %p= @community.email

    .mt-3.card
      .card-body
        %strong Eventos que realizamos


-# ========== mobile version ==========
-# %nav{"aria-label" => "breadcrumb"}
  .breadcrumb.bg-primary
    .container
      %ol.breadcrumb.bg-primary
        -# %li.breadcrumb-item
          %a.link-dark{:href => "/"}
            %i.fas.fa-home
        %li.breadcrumb-item
          %a.link-dark{:href => communities_path}= t('base.communities')
        -# %li.breadcrumb-item.active{"aria-current" => "page"}= @community.name
-# .show-community
  .bg-bar-community
    .container
      %h2.text-left.link-white= @community.name

  .container
    %p#notice= notice
    / community image
    = image_tag 'https://42f2671d685f51e10fc6-b9fcecea3e50b3b59bdc28dead054ebc.ssl.cf5.rackcdn.com/illustrations/good_team_m7uu.svg', width: '50%'

    - missingData = []
    %p
      = @community.about
    = verifyFields @community
    - if @community.address.present?
      %p
        %strong Dirección:
        = @community.address
    - else
      - missingData << @community.address

    - if @community.phone.present?
      %p
        %strong Teléfono de contacto:
        = @community.phone
    - else
      - missingData << @community.phone

    - if @community.email.present?
      %p
        %strong Correo electrónico:
        = @community.email
    - else
      - missingData << @community.email

    = link_to 'Edit', edit_community_path(@community)
    |
    = link_to 'Back', communities_path