config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :events
  resources :communities
  resources :sites
  resources :comunas
  resources :profiles

  get 'sites/comuna/load_sites', to: 'sites#load_sites', as: :load_sites

  get 'communities/comuna/load_communities', to: 'communities#load_communities', as: :load_communities

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :mix_categories
  has_many :communities, through: :mix_categories

  has_many :mix_categories
  has_many :sites, through: :mix_categories

  has_many :mix_categories
  has_many :events, through: :mix_categories
end

app/models/community.rb
class Community < ApplicationRecord
  # has_many :community_sites, class_name: 'CommunitySite'
  # has_many :sites, through: :community_sites
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User'

  has_many :maul_plans
  has_many :sites, through: :maul_plans

  has_many :community_mauls
  has_many :events, through: :community_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture
end

app/models/community_maul.rb
class CommunityMaul < ApplicationRecord
  belongs_to :community
  belongs_to :event
end

app/models/community_site.rb
class CommunitySite < ApplicationRecord
  belongs_to :communities, class_name: 'Community'
  belongs_to :sites, class_name: 'Site'
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  has_many :community, class_name: 'Community'
  has_many :site
  has_many :event
end

app/models/event.rb
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User', optional: true

  has_many :mix_categories
  has_many :communities, through: :community_mauls

  has_many :site_mauls
  has_many :sites, through: :site_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture

end

app/models/maul_plan.rb
class MaulPlan < ApplicationRecord
  belongs_to :community
  belongs_to :site
end

app/models/mix_category.rb
class MixCategory < ApplicationRecord
  belongs_to :community
  belongs_to :site
  belongs_to :event
  belongs_to :category
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  # validates_uniqueness_of :user_id
  # validates_uniqueness_of :profile, scope: :nickname, :message => "Nombre de usuario no disponible"
  # validate :nickname_uniqueness

  # protected
  
  # def nickname_uniqueness
  #   errors.add(:nickname, 'Nombre de usuario no disponible') if Profile.where('nickname' => nickname).exists?
  # end
end

app/models/site.rb
class Site < ApplicationRecord
  # has_many :community_sites, class_name: 'CommunitySite'
  # has_many :communities, through: :community_sites
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User', optional: true

  has_many :maul_plans
  has_many :communities, through: :maul_plans
  accepts_nested_attributes_for :communities, allow_destroy: true

  has_many :site_mauls
  has_many :events, through: :site_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture
end

app/models/site_maul.rb
class SiteMaul < ApplicationRecord
  belongs_to :site
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # extend FriendlyId
  # friendly_id :name, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :profile, depent: :destroy
  has_one :profile
  after_create :create_profile

  has_many :community, class_name: 'Community'
  has_many :site, class_name: 'Site'
  has_many :event, class_name: 'Event'

  def create_profile
    Profile.create(user: self)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  NETWORKS = [
    'website',
    'facebook',
    'instagram',
    'twitter',
    'youtube'
  ]
  def networks_section(site)
    links = []
    # NETWORKS.each do |n|
      # case site[:n].present?
      # when true
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end
      # if site[:n] != nil
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end

      # site[:n].present? == true ? links << content_tag(:i, image_tag("icons/#{n}.svg")) : nil

      # links << content_tag(:i, image_tag("icons/#{n}.svg"))
    # end
    if site.website.present?
      links << content_tag(:i, link_to(image_tag("icons/website.svg"), site.website, target: '_blank', class: 'link-svg'))
    end
    if site.facebook.present?
      links << content_tag(:i, link_to(image_tag("icons/facebook.svg"), site.facebook, target: '_blank', class: 'link-svg'))
    end
    if site.twitter.present?
      links << content_tag(:i, link_to(image_tag("icons/twitter.svg"), site.twitter, target: '_blank', class: 'link-svg'))
    end
    if site.instagram.present?
      links << content_tag(:i, link_to(image_tag("icons/instagram.svg"), site.instagram, target: '_blank', class: 'link-svg'))
    end
    if site.youtube.present?
      links << content_tag(:i, link_to(image_tag("icons/youtube.svg"), site.youtube, target: '_blank', class: 'link-svg'))
    end
    links.join.html_safe
  end
end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.mt-70
  .container
    = link_to (image_tag 'base/maul_logo_red_blur.png'), '/', class: 'navbar-brand image-logo'
    %button.float-right.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarText.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item.active
          .nav-link= link_to 'Comunidades', communities_path
        %li.nav-item
          .nav-link= link_to 'Sitios', sites_path
        %li.nav-item
          .nav-link= link_to 'Eventos', events_path
        - if user_signed_in?
          %li.nav-item.dropdown
            -# .nav-link= link_to current_user.email, '#', id: 'dropdownOptions', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'
            %a.nav-link.dropdown-toggle{:href => "#", id: 'dropdownOptions', "data-toggle"=>"dropdown", "aria-haspopup"=>"true", "aria-expanded"=>"true"} Mi Cuenta
            %ul.dropdown-menu{"aria-labelledby"=>"dropdownOptions"}
              %li.dropdown-item= link_to 'Actualizar Perfil', edit_profile_path(current_user.profile.id)
              -# %li.dropdown-item= link_to 'Modificar la cuenta', edit_user_registration_path
              %li.dropdown-item= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete
        - else
          %li.nav-item
            .nav-link= link_to 'Registrarse', new_user_registration_path
          %li.nav-item
            .nav-link= link_to 'Iniciar Sesión', new_user_session_path

      -# %span.navbar-text
      -#   text

app/views/shared/base/_footer.html.haml
/ Footer
%footer
  .maul-footer
    .maul-footer--logo
      = link_to (image_tag 'base/maul_logo_red_blur.png'), '/'
    .footer-title.text-center
      MAUL PROJECT
    .footer-text.text-center
      = link_to  'Sobre el proyecto', '#', class: 'link-white'
      |
      = link_to 'Términos y Condiciones', '#', class: 'link-white'
    -# .footer-text.text-center.row
      .col-6.text-right
        Sobre el proyecto
      .col-6.text-left
        Términos y Condiciones
    .col-12.text-center
      .footer-text
        Developed By:
        %a{:href => "https://github.com/SamZapata", :target => "_blank", class: 'link-red'} @samzapata

app/views/shared/base/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.mt-70
  .container
    .home-btn= link_to (image_tag 'base/maul_logo_red_blur.png'), '/', class: 'navbar-brand image-logo'
    %button.float-right.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarText.collapse.navbar-collapse.main-menu
      %ul.navbar-nav.ml-auto
        %li.nav-item.active
          .nav-link= link_to 'Comunidades', communities_path
        %li.nav-item
          .nav-link= link_to 'Sitios', sites_path
        %li.nav-item
          .nav-link= link_to 'Eventos', events_path
        - if user_signed_in?
          %li.nav-item.dropdown
            -# .nav-link= link_to current_user.email, '#', id: 'dropdownOptions', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'
            %a.nav-link.dropdown-toggle{:href => "#", id: 'dropdownOptions', "data-toggle"=>"dropdown", "aria-haspopup"=>"true", "aria-expanded"=>"true", class: 'link-dropdown-menu'} Mi Cuenta
            %ul.dropdown-menu{"aria-labelledby"=>"dropdownOptions"}
              %li.dropdown-item= link_to 'Actualizar Perfil', edit_profile_path(current_user.profile.id), class: 'link-dropdown'
              -# %li.dropdown-item= link_to 'Modificar la cuenta', edit_user_registration_path
              %li.dropdown-item= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'link-dropdown'
        - else
          %li.nav-item
            .nav-link= link_to 'Registrarse', new_user_registration_path
          %li.nav-item
            .nav-link= link_to 'Iniciar Sesión', new_user_session_path

      -# %span.navbar-text
      -#   text

app/views/shared/smartphone/__footer.html.haml
/ Footer
%footer
  .panel-footer
    .row
      .container.col-lg-4
        %h5.menu-header MAUL PROJECT
        %span
          %a.social-footer.social-icon{:href => "#", :target => "_blank"}
            %i.fa.fa-facebook
          %a.social-footer.social-icon{:href => "#", :target => "_blank"}
            %i.fa.fa-twitter
      .container.col-lg-4
        %h6.footer-text Sobre el proyecto:
        %a{:href => "/project/about"}
          %h6 ¿Que es Maul Project?
        %a{:href => "/project/information"}
          %h6 ¿Como Surge?
      .container.col-lg-4
        %h6.footer-text Recursos:
        %a{:href => "/project/terms-of-services"}
          %h6 Terminos Y Condiciones de Uso
        %a{:href => "#"}
          %h6 Proyección
    .container.col-lg-12.text-center
      %h6
        Developed By:
        %a{:href => "https://github.com/SamZapata", :target => "_blank"} @samzapata

app/views/shared/smartphone/_footer.html.haml
/ Footer
%footer
  .maul-footer
    .maul-footer--logo
      = link_to (image_tag 'base/maul_logo_red_blur.png'), '/'
    .footer-title.text-center
      MAUL PROJECT
    .footer-text.text-center.row
      .col-6.text-right
        = link_to  'Sobre el proyecto', '#', class: 'link-white'
      .col-6.text-left.border-left
        = link_to 'Términos y Condiciones', '#', class: 'link-white'
    .col-12.text-center
      .footer-text
        Developed By:
        %a{:href => "https://github.com/SamZapata", :target => "_blank", class: 'link-red'} @samzapata
  -# .maul-footer
    .row
      .container.col-lg-4
        %h5.menu-header MAUL PROJECT
        %span
          %a.social-footer.social-icon{:href => "#", :target => "_blank"}
            %i.fa.fa-facebook
          %a.social-footer.social-icon{:href => "#", :target => "_blank"}
            %i.fa.fa-twitter
      .container.col-lg-4
        %h6.footer-text Sobre el proyecto:
        %a{:href => "/project/about"}
          %h6 ¿Que es Maul Project?
        %a{:href => "/project/information"}
          %h6 ¿Como Surge?
      .container.col-lg-4
        %h6.footer-text Recursos:
        %a{:href => "/project/terms-of-services"}
          %h6 Terminos Y Condiciones de Uso
        %a{:href => "#"}
          %h6 Proyección
    .container.col-lg-12.text-center
      %h6
        Developed By:
        %a{:href => "https://github.com/SamZapata", :target => "_blank"} @samzapata

app/views/shared/smartphone/_navbar.html.haml
-# mobile version for navbar menu
.m-main-menu
  .m-navbar.d-flex.justify-content-center
    .container.d-flex.justify-around
      .col-4.text-center.d-flex.align-items-center.justify-content-start
        = link_to '#', class: 'm-home-text', "data-toggle"=>"modal", "data-target"=>"#maulProjectModal" do
          %i.fa.fa-bars.fa-2x
      .col-4.text-center.d-flex.align-items-center
        .m-home-btn= link_to (image_tag 'base/maul_logo_red_blur.png'), '/', class: 'navbar-brand m-image-logo'
      .col-4.text-center.d-flex.align-items-center.justify-content-end
        - if user_signed_in?
          = link_to '', "data-toggle"=>"modal", "data-target"=>"#profileModal", class: 'm-home-text' do
            %i.fa.fa-user-edit.fa-2x
        - else
          =link_to '', class: 'm-home-text', "data-toggle"=>"modal", "data-target"=>"#accountModal" do
            %i.fa.fa-user.fa-2x


  / Modal for Maul Project menu
  #maulProjectModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "maulProjectModal", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content.modal-menu
        .modal-header
          %h2#maulProjectModalTitle.modal-title Maul Project
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true", class: 'link-white'}
              %i.fa.fa-times.fa-2x
        .modal-body.d-flex.flex-column
          .btn-selection__communities.text-center
            = link_to t('mainmenu.communities'), communities_path, class: 'link-white'
          .btn-selection__sites.text-center
            = link_to t('mainmenu.sites'), sites_path, class: 'link-white'
          .btn-selection__events.text-center
            = link_to t('mainmenu.events'), events_path, class: 'link-white'
          -# .mt-auto.p-2.ml-auto
            -# = link_to t('mainmenu.about_maul'), '#', class: 'link-white'

  / Modal for profile
  #profileModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "profileModal", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content.modal-menu
        -# .modal-header
          %h5#profileModalTitle.modal-title Modal title PROFILE
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body.d-flex.flex-column
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true", class: 'link-white'}
              %i.fa.fa-times.fa-2x
          - if user_signed_in?
            .btn-selection__base.text-center
              = link_to 'Actualizar Perfil', edit_profile_path(current_user.profile.id), class: 'link-white'
            .btn-selection__base.text-center
              = link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'link-white'
            -# .mt-auto.p-2.ml-auto
              = link_to t('mainmenu.about_maul'), '#', class: 'link-white'

  / Modal for account
  #accountModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "profileModal", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content.modal-menu
        .modal-body.d-flex.flex-column
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true", class: 'link-white'}
              %i.fa.fa-times.fa-2x
          .btn-selection__base.text-center
            =  link_to 'Registrarse', new_user_registration_path, class: 'link-white'
          .btn-selection__base.text-center
            = link_to 'Iniciar Sesión', new_user_session_path, class: 'link-white'
          -# .mt-auto.ml-auto.p-2
            = link_to t('mainmenu.about_maul'), '#', class: 'link-white'