config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :events
  resources :communities
  resources :sites
  resources :comunas
  resources :profiles

  get 'sites/comuna/load_sites', to: 'sites#load_sites', as: :load_sites

  get 'communities/comuna/load_communities', to: 'communities#load_communities', as: :load_communities

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/site.rb
class Site < ApplicationRecord
  # has_many :community_sites, class_name: 'CommunitySite'
  # has_many :communities, through: :community_sites
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :comuna, class_name: 'Comuna', optional: true
  belongs_to :user, class_name: 'User', optional: true

  has_many :maul_plans
  has_many :communities, through: :maul_plans
  accepts_nested_attributes_for :communities, allow_destroy: true

  has_many :site_mauls
  has_many :events, through: :site_mauls

  has_many :mix_categories
  has_many :categories, through: :mix_categories

  # upload images
  has_one_attached :picture
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  def load_sites
    @comuna = Comuna.find(params[:comuna_id])
    @sites = Site.where(comuna_id: @comuna)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.friendly.find(params[:id])
    @site_networks = Sites::CheckSite.new.call @site
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @site.save
        # add_community(site_params[:id])
        format.html { redirect_to @site, notice: 'Sitio creado exitosamente.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    # @site = Site.find(params[:id])
    @site = Site.friendly.find(params[:id])
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'El sitio fué actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :index }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.friendly.find(params[:id])
      # @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :address, :map, :phone, :about, :comuna_id, :picture, :website, :facebook, :instagram, :twitter, :youtube,
        community_ids: [],
        event_ids: [],
        category_ids: []
      )
    end

    # def add_community(community_ids)
      # if community_ids != nil
      #   # @new_community = Community.create(name: 'un site me creó')
      #   # @new_community.save
      # end
    # end
end

app/helpers/sites_helper.rb
module SitesHelper
  NETWORKS = [
    'website',
    'facebook',
    'instagram',
    'twitter',
    'youtube'
  ]
  def networks_section(site)
    links = []
    # NETWORKS.each do |n|
      # case site[:n].present?
      # when true
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end
      # if site[:n] != nil
      #   links << content_tag(:i, image_tag("icons/#{n}.svg"))
      # end

      # site[:n].present? == true ? links << content_tag(:i, image_tag("icons/#{n}.svg")) : nil

      # links << content_tag(:i, image_tag("icons/#{n}.svg"))
    # end
    if site.website.present?
      links << content_tag(:i, link_to(image_tag("icons/website.svg"), site.website, target: '_blank', class: 'link-svg'))
    end
    if site.facebook.present?
      links << content_tag(:i, link_to(image_tag("icons/facebook.svg"), site.facebook, target: '_blank', class: 'link-svg'))
    end
    if site.twitter.present?
      links << content_tag(:i, link_to(image_tag("icons/twitter.svg"), site.twitter, target: '_blank', class: 'link-svg'))
    end
    if site.instagram.present?
      links << content_tag(:i, link_to(image_tag("icons/instagram.svg"), site.instagram, target: '_blank', class: 'link-svg'))
    end
    if site.youtube.present?
      links << content_tag(:i, link_to(image_tag("icons/youtube.svg"), site.youtube, target: '_blank', class: 'link-svg'))
    end
    links.join.html_safe
  end
end

app/views/sites/smartphone/_index.html.haml
.index-sites
  .bg-bar-site
    .container.d-flex.justify-content-between.mt-2
      %h5.d-flex.align-items-center= link_to t('base.sites'), sites_path, alt: 'index sites', class: 'link-white'
      %h6.d-flex.align-items-center
        %em.link-white.fa.fa-map-marked-alt.mr-2
        %em= link_to t('site.register_a_site'), new_site_path, class: 'link-white'
  %p#notice= notice

  .d-flex.justify-content-center
    %ul#tabSites.nav.nav-tabs{:role => "tablist"}
      %li.nav-item
        %a#all-tab.nav-link.active{"aria-controls" => "all", "aria-selected" => "true", "data-toggle" => "tab", :href => "#all", :role => "tab", class: 'link-site'} Todos
      -# %li.nav-item
        %a#category-tab.nav-link{"aria-controls" => "category", "aria-selected" => "false", "data-toggle" => "tab", :href => "#category", :role => "tab", class: 'link-site'} Categorías
      %li.nav-item
        %a#comunas-tab.nav-link{"aria-controls" => "comunas", "aria-selected" => "false", "data-toggle" => "tab", :href => "#comunas", :role => "tab", class: 'link-site'} Comunas

  #tabSitesContent.tab-content
    #all.tab-pane.fade.show.active{"aria-labelledby" => "all-tab", :role => "tabpanel"}
      .container
        .mt-3.pt-3 Sitios registrados en Maul Project
        .card-columns
          - @sites.each do |site|
            .box-index.card.p-2.mt-5
              %blockquote.blockquote.mb-0
                .card-body.bg-card
                  - if site.picture.attached?
                    = image_tag site.picture
                  - else
                    = image_tag "base/elements_svg/undraw_reminder_pa79.svg"
                  =link_to site.name, site, class: 'card-title'
                -# %footer
                  .text-right temática 1, temática 2...

    #category.tab-pane.fade{"aria-labelledby" => "category-tab", :role => "tabpanel"} ...
    #comunas.tab-pane.fade{"aria-labelledby" => "comunas-tab", :role => "tabpanel"}
      .container
        .d-flex.justify-content-around
          -# .mt-3 Selecciona una comuna
          .mt-3.btn-group
            %button.btn{ type: 'button'} selecciona una comuna
            %button.btn.btn-danger.dropdown-toggle.dropdown-toggle-split{ 'data-toggle' => 'dropdown', 'aria-haspopup' => true, 'aria-expanded' => false }
              %span.sr-only Toggle Dropdown
            .dropdown-menu
              - Comuna.all.each do |comuna|
                = link_to comuna.name, load_sites_path(comuna_id: comuna.id), class: 'dropdown-item', remote: true

        .content-tab-comunas
          .mt-3.pt-3.selected-comuna
            - com_13 = []
            - @sites.map do |site|
              - if site.comuna_id == 13
                - com_13 << site
            = "Comuna 13, se encontraron #{com_13.length} sitios registrados"
          .card-columns
            - @sites.each do |site|
              - if site.comuna_id == 13
                .box-index.card.p-2.mt-5
                  %blockquote.blockquote.mb-0
                    .card-body.bg-card
                      - if site.picture.attached?
                        = image_tag site.picture
                      - else
                        = image_tag "base/elements_svg/undraw_reminder_pa79.svg"
                      =link_to site.name, site, class: 'card-title'

:javascript
  MAUL.comunas.dropdown.setup();



-# .m.index-sites
  .bg-bar-site
    .container.d-flex.justify-content-between.mt-2
      %h1.d-flex.align-items-center= link_to t('base.sites'), sites_path, alt: 'index sites', class: 'link-white'
      %h2.d-flex.align-items-center
        %em.link-white.fa.fa-map-marked-alt.mr-2
        %em= link_to t('site.register_a_site'), new_site_path, class: 'link-white'
  %p#notice= notice

  .d-flex.justify-content-center
    %ul#tabSites.nav.nav-tabs{:role => "tablist"}
      %li.nav-item
        %a#all-tab.nav-link.active{"aria-controls" => "all", "aria-selected" => "true", "data-toggle" => "tab", :href => "#all", :role => "tab", class: 'link-site'} Todos
      -# %li.nav-item
        %a#category-tab.nav-link{"aria-controls" => "category", "aria-selected" => "false", "data-toggle" => "tab", :href => "#category", :role => "tab", class: 'link-site'} Categorías
      %li.nav-item
        %a#comunas-tab.nav-link{"aria-controls" => "comunas", "aria-selected" => "false", "data-toggle" => "tab", :href => "#comunas", :role => "tab", class: 'link-site'} Comunas

  #tabSitesContent.tab-content
    #all.tab-pane.fade.show.active{"aria-labelledby" => "all-tab", :role => "tabpanel"}
      .container
        - @sites.each do |site|
          .box-index.card.p-2.mt-4
            %blockquote.blockquote.mb-0
              .card-body.bg-card
                = image_tag "base/elements_svg/undraw_reminder_pa79.svg", width: '50%'
                =link_to site.name, site, class: 'card-title'
              %footer
                .text-right temática 1, temática 2...

    #category.tab-pane.fade{"aria-labelledby" => "category-tab", :role => "tabpanel"} ...
    #comunas.tab-pane.fade{"aria-labelledby" => "comunas-tab", :role => "tabpanel"} ...

app/views/sites/smartphone/_new.html.haml
.bg-bar-site
  .container
    %h2.text-left.link-white= t('site.register_form')

.container.d-flex.flex-column.mt-4
  .card
    .card-body.needs-validation
    - site = @site
    .text-justify
      = form_with(model: site, local: true) do |form|
        - if site.errors.any?
          #error_explanation
            %h2
              = pluralize(site.errors.count, "error")
              prohibited this site from being saved:
            %ul
              - site.errors.full_messages.each do |message|
                %li= message

        .field
          = form.label :name
          = form.text_field :name
        .field
          = form.label :address
          = form.text_field :address
        .field
          = form.label :map
          = form.text_field :map
        .field
          = form.label :phone
          = form.text_field :phone
        .field
          = form.label :about
          = form.text_area :about
        .field
          = form.label :community
          = form.collection_select :community_ids, Community.all, :id, :name
        .actions
          = form.submit

app/views/sites/smartphone/_show.html.haml
-# show site mobile version
-# author: Johnny Zapata

.show-site
  %nav{"aria-label" => "breadcrumb"}
    .bg-bar-site
      .container
        %ol.breadcrumb
          %li.breadcrumb-item
            %a.link-white{:href => "/"}
              %i.fas.fa-home
          %li.breadcrumb-item
            %a.link-white{:href => sites_path}= t('base.sites')
          %li.breadcrumb-item.active{"aria-current" => "page"}= @site.name
  .container.text-center
    %p#notice= notice
    - if user_signed_in? && current_user.id == @site.user_id
      .show-site-edit
        = link_to edit_site_path(@site), class: 'link-dark' do
          %i.fa.fa-edit
    %h1.mt-3= @site.name
    %hr.mb-2
    .site-networks-section
      = networks_section @site
    .mt-3= image_tag(@site.picture, width: 200) if @site.picture.attached?
    .mt-3.card
      .card-body.text-left
        %strong= t('site.about_site')
        %p
          = @site.about
        %p
          %strong= t('site.address') + ': '
          = @site.address
        %p
          %strong= t('site.phone') + ': '
          = @site.phone

    .mt-3.d-flex.justify-content-center
      %iframe{ src: @site.map.gsub(/<iframe src="|" width="400" height="300" frameborder="0" style="border:0" allowfullscreen><|iframe>/,""), width: '100%', height: '400px'}

    .mt-3.card
      .card-body
        .d-flex.justify-content-center
          %ul#tabSitesRelation.nav.nav-tabs{:role => "tablist"}
            %li.nav-item
              %a#communities-tab.nav-link.active{"aria-controls" => "data", "aria-selected" => "true", "data-toggle" => "tab", :href => "#communities", :role => "tab", class: 'link-dark'}= t('base.communities')
            %li.nav-item
              %a#events-tab.nav-link{"aria-controls" => "events", "aria-selected" => "false", "data-toggle" => "tab", :href => "#events", :role => "tab", class: 'link-dark'}= t('base.events')
        #tabSitesRelation.tab-content
          #communities.tab-pane.fade.show.active{"aria-labelledby" => "communities-tab", :role => "tabpanel"}
            .text-left Comunidades que aquí se reunen:
            - if @site.communities.count != 0
              .text-left
                - @site.communities.each do |community|
                  - community.slug == nil ? slug = community.id : slug = community.slug
                  = link_to "/communities/#{slug}", class: 'link-dark' do
                    .fa.fa-users
                    = community.name
                  %br
            - else
              Aún no hay comunidades asociadas a este sitio

          #events.tab-pane.fade{"aria-labelledby" => "events-tab", :role => "tabpanel"}
            .text-left Eventos que se realizan aquí:
            - if @site.events.count != 0
              .text-left
                - @site.events.each do |event|
                  = link_to "/events/#{event.id}", class: 'link-dark' do
                    .fa.fa-calendar-alt
                    = event.name
            - else
              Aún no hay eventos asociados a este sitio



-# ======= mobile version =======
-# .show-site
  .bg-bar-site
    .container
      %h2.text-left.link-white= @site.name

  -# .content-site
    / site image
    = image_tag "base/elements_svg/undraw_reminder_pa79.svg", alt: 'image '
    %p#notice= notice
  .container
    %p#notice= notice
    %h1.mt-3.text-left= @site.name
    %hr.mb-1
    .site-networks-section.mb-1
      %i
        = image_tag 'icons/webpage.svg'
      %i
        = image_tag 'icons/facebook.svg'
      %i
        = image_tag 'icons/instagram.svg'
      %i
        = image_tag 'icons/twitter.svg'
      %i
        = image_tag 'icons/youtube.svg'









-# ----------------------------------------------------
-# .show-site
  .bg-bar-site
    .container
      %h2.text-left.link-white= @site.name

  .container
    / site image
    = image_tag "base/elements_svg/undraw_reminder_pa79.svg", alt: 'image ', width: '50%'
    %p#notice= notice

    - missingData = []
    %p
      = @site.about
    .d-flex.justify-content-center
      %iframe{ src: @site.map.gsub(/<iframe src="|" width="400" height="300" frameborder="0" style="border:0" allowfullscreen><|iframe>/,""), width: '100%', height: '400px'}
    = link_to 'Edit', edit_site_path(@site)

    -# = verifyFields @site
    - if @site.address.present?
      %p
        %strong Dirección:
        = @site.address
    - else
      - missingData << @site.address

    - if @site.phone.present?
      %p
        %strong Teléfono de contacto:
        = @site.phone
    - else
      - missingData << @site.phone

    = link_to 'Edit', edit_site_path(@site)
    |
    = link_to 'Back', sites_path